dbt_tutorial:
  outputs:
    dev:
      database: hr_analytics
      driver: ODBC Driver 17 for SQL Server
      port: 1433
      schema: dbo
      server: localhost\SQLEXPRESS
      threads: 1
      trust_cert: true
      type: sqlserver
      windows_login: true
  target: dev
sample_dbt_project:
  outputs:
    dev:
      database: dbt_sample
      driver: ODBC Driver 17 for SQL Server
      port: 1433
      schema: dbo
      server: localhost\SQLEXPRESS
      threads: 1
      trust_cert: true
      type: sqlserver
      windows_login: true
  target: dev
