version: 2

sources:
  - name: dbt_tutorial
    schema: dbo
    tables:
      - name: raw_employees
      - name: raw_performance

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: employee_rankings
    description: "Aggregates employee performance and categorizes them into tiers"
    columns:
      - name: employee_id
        description: "Unique employee ID"
        tests:
          - not_null
          - unique
      - name: avg_rating
        description: "Average of all yearly performance ratings"
      - name: performance_tier
        description: "Performance category based on average rating"
        tests:
          - accepted_values:
              values: ['Rank1', 'Rank2', 'Rank3', 'Rank4']

    data_tests:
      - engineering_rating_check_macro: {}

  - name: bonus_variable_example
    description: "Calculates adjusted_bonus using a set variable multiplier."
    columns:
      - name: employee_id
        description: "Employee ID"
        tests:
          - not_null
      - name: adjusted_bonus
        description: "Bonus adjusted using variable multiplier"

  - name: bonus_macro_example
    description: "Uses a macro to calculate adjusted_bonus with a 1.1 multiplier."
    columns:
      - name: employee_id
        description: "Employee ID"
        tests:
          - not_null
      - name: adjusted_bonus
        description: "Bonus adjusted using macro"

  - name: department_HireDate_filter_example
    description: "Applies HireDate threshold conditionally based on selected department."
    columns:
      - name: employee_id
        description: "Employee ID"
      - name: hire_date
        description: "HireDate filtered based on department"

  - name: loop_select_columns_example
    description: "Selects employee details using a macro that loops over column names."
    columns:
      - name: employee_id
        description: "Employee ID"
        tests:
          - not_null
      - name: first_name
        description: "First name of the employee"
      - name: last_name
        description: "Last name of the employee"
      - name: department
        description: "Department name"
